### ISSUE TITLE
Rename "Getting Started" section in docs to "Deploy Resoto"

### ISSUE THREAD

**Issue by scapecast** [someengineering/resoto.com#185]
### Description

I'd like us to be specific, and also use active language.

from our homepage, the CTA button "deploy now" will link to the  "deploy Resoto" section. 

I'm open to call it something else - "Install" - just not "getting started".

**Comment by TheCatLady** [comment]
We now have an "Installation" section (in addition to others) within "Getting Started"; closing this issue.
