### ISSUE TITLE
Documentation for AWS Role Policies/Permissions

### ISSUE THREAD

**Issue by smaud** [someengineering/resoto.com#82]
I'm running x3 EC2 instances, but not getting anything listed ```kind aws_ec2_instance```, and I suspect is it my AWS IAM User permissions.

What permissions/AWS managed policies does the  AWS IAM User require to run cloudkeeper in docker?

**Comment by TheCatLady** [comment]
https://resoto.com/docs/reference/permissions#aws-permissions
